### ISSUE TITLE
ref_lid_collection error when ingesting data sets

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-mgr#57] opened 2022-10-06 18:21 UTC
## 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/33492486/194389086-1cd773ef-1ccc-4e48-8ddd-1b95c49b7d1f.png)

## 🕵️ Expected behavior

Change archive status for the collection

## 🖥 System Info

---

## ⚙️ Engineering Details
Initial guess for this error is because the first product ingested only included 1 collection reference, so harvest/registry manager created the schema as a string value instead of an array.

Duplicate of https://github.com/NASA-PDS/registry/issues/118 but keeping open to ensure traceability.

**Comment by alexdunnjpl** [comment] 2022-11-10 20:02
Likely a red herring, but looking at [the function which builds the JSON for the update request](https://github.com/NASA-PDS/registry-common/blob/main/src/main/java/gov/nasa/pds/registry/common/es/dao/ProductRequestBuilder.java#L24) it doesn't actually build valid JSON (unless the ES client supports multiple newline-separated JSON payloads attached to a single `Request` - I haven't been able to determine that yet.

```json
{ "update" : {"_id" : "urn:nasa:pds:epoxi_mri::1.0" } }
{ "doc" : {"ops:Tracking_Meta/ops:archive_status" : "archived"} }
```

**Comment by alexdunnjpl** [comment] 2022-11-10 20:20
@jordanpadams 

> This may be fixed already.

General guess, or is there a specific release or related issue you're thinking of?

**Comment by alexdunnjpl** [comment] 2022-11-17 23:34
Bug appears to be triggering due to the relevant bundle containing only one collection.

The response returned by [the API request](https://search-sbnumd-prod-o5i2rnn265gnwmv2quk4n7uram.us-west-2.es.amazonaws.com/registry/_doc/urn:nasa:pds:epoxi_mri::1.0?_source=ref_lidvid_collection,ref_lid_collection) during `es.dao.ProductDao.getCollectionIds()` is as follows:

```json
{
  "_index": "registry",
  "_type": "_doc",
  "_id": "urn:nasa:pds:epoxi_mri::1.0",
  "_version": 2,
  "_seq_no": 27012,
  "_primary_term": 3,
  "found": true,
  "_source": {
    "ref_lid_collection": "urn:nasa:pds:epoxi_mri:hartley2_photometry"
  }
}
```

with `ref_lid_collection` being parsed by `es.dao.DaoUtils.parseSet()`, which expects to encounter an array-like JSON string (as opposed to the unenclosed string).

@jordanpadams this appears to be the fault of the API.  Will follow up when I identify the relevant next steps.

**Comment by alexdunnjpl** [comment] 2022-11-17 23:51
Confirmed that [the same request for a bundle with multiple collections](https://search-sbnumd-prod-o5i2rnn265gnwmv2quk4n7uram.us-west-2.es.amazonaws.com/registry/_doc/urn:nasa:pds:dart_teleobs::1.0?_source=ref_lidvid_collection,ref_lid_collection) does not have this issue and correctly returns an array of strings.

```json
{
  "_index": "registry",
  "_type": "_doc",
  "_id": "urn:nasa:pds:dart_teleobs::1.0",
  "_version": 1,
  "_seq_no": 24385,
  "_primary_term": 3,
  "found": true,
  "_source": {
    "ref_lidvid_collection": [
      "urn:nasa:pds:dart_teleobs:data_ldtcal::1.0",
      "urn:nasa:pds:dart_teleobs:data_ldtddp::1.0",
      "urn:nasa:pds:dart_teleobs:data_ldtraw::1.0",
      "urn:nasa:pds:dart_teleobs:document_ldt::1.0"
    ],
    "ref_lid_collection": [
      "urn:nasa:pds:dart_teleobs:data_ldtcal",
      "urn:nasa:pds:dart_teleobs:data_ldtddp",
      "urn:nasa:pds:dart_teleobs:data_ldtraw",
      "urn:nasa:pds:dart_teleobs:document_ldt"
    ]
  }
}
```

**Comment by alexdunnjpl** [comment] 2022-11-17 23:53
@jordanpadams @al-niessner @jimmie @nutjob4life is it `registry-loader` that is responsible for constructing the docs to be loaded into the registry? (inb4 yeah bro, it's in the name)

**Comment by jordanpadams** [comment] 2022-11-21 17:38
@alexdunnjpl [Harvest](https://github.com/NASA-PDS/harvest/) is the tool for doing this. we discussed merging registry-mgr and harvest into that registry-loader repo, but it has not happened.

**Comment by alexdunnjpl** [comment] 2022-11-21 17:43
Thanks Jordan - should be able to continue with this now.

**Comment by jordanpadams** [comment] 2022-11-21 17:43
@alexdunnjpl hopefully the harvest update will work. we may also need to update the `ref_lid_collection` type to be an array versus a String. it may have been the first bundle they ingested only contained 1 collection, which OpenSearch then dynamically typed as a String instead of an array

**Comment by jordanpadams** [comment] 2022-11-21 17:44
Oops! Nevermind. deleted previous comment because I was definitely wrong. Hopefully the harvest fix will make it work.

**Comment by alexdunnjpl** [comment] 2022-11-23 03:28
Closing as this is a `registry-common` issue.

[A corresponding issue has been opened in `registry-common`)[https://github.com/NASA-PDS/registry-mgr/issues/57}

**Closed by alexdunnjpl** 2022-11-23 03:28 UTC
Labels: bug, B13.1, sprint-backlog, s.medium
